# Generated by Django 5.0.2 on 2024-02-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto_eletronico', '0002_pontoeletronico'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='regime_horas',
            field=models.IntegerField(default=8),
        ),
    ]
