# Generated by Django 5.0.2 on 2024-02-25 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto_eletronico', '0003_customuser_regime_horas'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ponto_eletronico.empresa'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='regime_horas',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
    ]
